import { db } from './connection';
import {
  roles,
  permissions,
  rolePermissions,
  orgRoles,
  orgPermissions,
  orgRolePermissions,
} from './schema';
import { eq, and } from 'drizzle-orm';
import { createLogger } from '../utils/logger';

const log = createLogger('Seed');

// ── System roles ─────────────────────────────────────────
// These are referenced in code (e.g. assignDefaultRole('user'))
// The app will not function without them
const SYSTEM_ROLES = [
  { name: 'user', description: 'Default role assigned to every new user' },
  { name: 'moderator', description: 'Can manage users and view audit logs' },
  { name: 'admin', description: 'Full system access' },
] as const;

// ── System permissions ───────────────────────────────────
// These are referenced in authorize() calls across routes
// The app will not function without them
const SYSTEM_PERMISSIONS = [
  { name: 'read:profile', resource: 'profile', action: 'read' },
  { name: 'write:profile', resource: 'profile', action: 'write' },
  { name: 'read:users', resource: 'users', action: 'read' },
  { name: 'write:users', resource: 'users', action: 'write' },
  { name: 'read:roles', resource: 'roles', action: 'read' },
  { name: 'write:roles', resource: 'roles', action: 'write' },
  { name: 'read:audit-logs', resource: 'audit-logs', action: 'read' },
] as const;

// ── Default role → permission mappings ───────────────────
// Starter config — admins can customize via API at runtime
const DEFAULT_ROLE_PERMISSIONS: Record<string, string[]> = {
  user: ['read:profile', 'write:profile'],
  moderator: [
    'read:profile',
    'write:profile',
    'read:users',
    'read:roles',
    'read:audit-logs',
  ],
  admin: [
    'read:profile',
    'write:profile',
    'read:users',
    'write:users',
    'read:roles',
    'write:roles',
    'read:audit-logs',
  ],
};

/**
 * Seeds system-required data into the database.
 *
 * Idempotent — safe to call on every app startup.
 * Uses ON CONFLICT DO NOTHING so it never duplicates rows.
 *
 * Call this:
 * - On app startup (before routes register)
 * - In test global-setup (after migrations)
 * - Via `npm run db:seed` for manual runs
 */
export async function seedSystemData(): Promise<void> {
  log.info('Seeding system data...');

  // Step 1 — Insert roles
  for (const role of SYSTEM_ROLES) {
    await db
      .insert(roles)
      .values(role)
      .onConflictDoNothing({ target: roles.name });
  }

  // Step 2 — Insert permissions
  for (const perm of SYSTEM_PERMISSIONS) {
    await db
      .insert(permissions)
      .values(perm)
      .onConflictDoNothing({ target: permissions.name });
  }

  // Step 3 — Map permissions to roles
  // Look up IDs since they're UUIDs generated by the DB
  for (const [roleName, permNames] of Object.entries(
    DEFAULT_ROLE_PERMISSIONS
  )) {
    const [role] = await db
      .select({ id: roles.id })
      .from(roles)
      .where(eq(roles.name, roleName));

    if (!role) continue;

    for (const permName of permNames) {
      const [perm] = await db
        .select({ id: permissions.id })
        .from(permissions)
        .where(eq(permissions.name, permName));

      if (!perm) continue;

      await db
        .insert(rolePermissions)
        .values({ roleId: role.id, permissionId: perm.id })
        .onConflictDoNothing();
    }
  }

  log.info('System data seeded successfully');
}

// ── Default org roles ───────────────────────────────────
// Seeded into every new organization on creation
// isSystem = true prevents accidental deletion
const DEFAULT_ORG_ROLES = [
  { name: 'owner', description: 'Full control over the organization' },
  { name: 'admin', description: 'Manage members, roles, and org settings' },
  { name: 'member', description: 'Default role for new members' },
] as const;

// ── Default org permissions ─────────────────────────────
// These map to authorizeOrg() checks in org-scoped routes
const DEFAULT_ORG_PERMISSIONS = [
  { name: 'read:org', resource: 'org', action: 'read' },
  { name: 'write:org', resource: 'org', action: 'write' },
  { name: 'delete:org', resource: 'org', action: 'delete' },
  { name: 'read:members', resource: 'members', action: 'read' },
  { name: 'write:members', resource: 'members', action: 'write' },
  { name: 'read:org-roles', resource: 'org-roles', action: 'read' },
  { name: 'write:org-roles', resource: 'org-roles', action: 'write' },
  { name: 'read:org-audit', resource: 'org-audit', action: 'read' },
] as const;

// ── Default org role → permission mappings ──────────────
// owner gets everything, admin gets most, member gets read-only
const DEFAULT_ORG_ROLE_PERMISSIONS: Record<string, string[]> = {
  owner: [
    'read:org',
    'write:org',
    'delete:org',
    'read:members',
    'write:members',
    'read:org-roles',
    'write:org-roles',
    'read:org-audit',
  ],
  admin: [
    'read:org',
    'write:org',
    'read:members',
    'write:members',
    'read:org-roles',
    'write:org-roles',
    'read:org-audit',
  ],
  member: ['read:org', 'read:members'],
};

/**
 * Seeds default roles and permissions for a newly created organization.
 *
 * Idempotent — uses composite unique index (orgId, name) via onConflictDoNothing.
 * Called from OrgService.create() after the org row is inserted.
 *
 * Why per-org instead of shared?
 * Each org gets its own copy so they can customize independently.
 * Org A's "billing-admin" doesn't leak into Org B.
 */
export async function seedOrgDefaults(orgId: string): Promise<void> {
  log.info({ orgId }, 'Seeding org defaults...');

  // Step 1 — Insert default org roles
  for (const role of DEFAULT_ORG_ROLES) {
    await db
      .insert(orgRoles)
      .values({ orgId, ...role, isSystem: true })
      .onConflictDoNothing();
  }

  // Step 2 — Insert default org permissions
  for (const perm of DEFAULT_ORG_PERMISSIONS) {
    await db
      .insert(orgPermissions)
      .values({ orgId, ...perm })
      .onConflictDoNothing();
  }

  // Step 3 — Map permissions to roles
  for (const [roleName, permNames] of Object.entries(
    DEFAULT_ORG_ROLE_PERMISSIONS
  )) {
    const [role] = await db
      .select({ id: orgRoles.id })
      .from(orgRoles)
      .where(and(eq(orgRoles.orgId, orgId), eq(orgRoles.name, roleName)));

    if (!role) continue;

    for (const permName of permNames) {
      const [perm] = await db
        .select({ id: orgPermissions.id })
        .from(orgPermissions)
        .where(
          and(
            eq(orgPermissions.orgId, orgId),
            eq(orgPermissions.name, permName)
          )
        );

      if (!perm) continue;

      await db
        .insert(orgRolePermissions)
        .values({ orgRoleId: role.id, orgPermissionId: perm.id })
        .onConflictDoNothing();
    }
  }

  log.info({ orgId }, 'Org defaults seeded successfully');
}
