import { db } from './connection';
import { roles, permissions, rolePermissions } from './schema';
import { eq } from 'drizzle-orm';
import { createLogger } from '../utils/logger';

const log = createLogger('Seed');

// ── System roles ─────────────────────────────────────────
// These are referenced in code (e.g. assignDefaultRole('user'))
// The app will not function without them
const SYSTEM_ROLES = [
  { name: 'user', description: 'Default role assigned to every new user' },
  { name: 'moderator', description: 'Can manage users and view audit logs' },
  { name: 'admin', description: 'Full system access' },
] as const;

// ── System permissions ───────────────────────────────────
// These are referenced in authorize() calls across routes
// The app will not function without them
const SYSTEM_PERMISSIONS = [
  { name: 'read:profile', resource: 'profile', action: 'read' },
  { name: 'write:profile', resource: 'profile', action: 'write' },
  { name: 'read:users', resource: 'users', action: 'read' },
  { name: 'write:users', resource: 'users', action: 'write' },
  { name: 'read:roles', resource: 'roles', action: 'read' },
  { name: 'write:roles', resource: 'roles', action: 'write' },
  { name: 'read:audit-logs', resource: 'audit-logs', action: 'read' },
] as const;

// ── Default role → permission mappings ───────────────────
// Starter config — admins can customize via API at runtime
const DEFAULT_ROLE_PERMISSIONS: Record<string, string[]> = {
  user: ['read:profile', 'write:profile'],
  moderator: [
    'read:profile',
    'write:profile',
    'read:users',
    'read:roles',
    'read:audit-logs',
  ],
  admin: [
    'read:profile',
    'write:profile',
    'read:users',
    'write:users',
    'read:roles',
    'write:roles',
    'read:audit-logs',
  ],
};

/**
 * Seeds system-required data into the database.
 *
 * Idempotent — safe to call on every app startup.
 * Uses ON CONFLICT DO NOTHING so it never duplicates rows.
 *
 * Call this:
 * - On app startup (before routes register)
 * - In test global-setup (after migrations)
 * - Via `npm run db:seed` for manual runs
 */
export async function seedSystemData(): Promise<void> {
  log.info('Seeding system data...');

  // Step 1 — Insert roles
  for (const role of SYSTEM_ROLES) {
    await db
      .insert(roles)
      .values(role)
      .onConflictDoNothing({ target: roles.name });
  }

  // Step 2 — Insert permissions
  for (const perm of SYSTEM_PERMISSIONS) {
    await db
      .insert(permissions)
      .values(perm)
      .onConflictDoNothing({ target: permissions.name });
  }

  // Step 3 — Map permissions to roles
  // Look up IDs since they're UUIDs generated by the DB
  for (const [roleName, permNames] of Object.entries(
    DEFAULT_ROLE_PERMISSIONS
  )) {
    const [role] = await db
      .select({ id: roles.id })
      .from(roles)
      .where(eq(roles.name, roleName));

    if (!role) continue;

    for (const permName of permNames) {
      const [perm] = await db
        .select({ id: permissions.id })
        .from(permissions)
        .where(eq(permissions.name, permName));

      if (!perm) continue;

      await db
        .insert(rolePermissions)
        .values({ roleId: role.id, permissionId: perm.id })
        .onConflictDoNothing();
    }
  }

  log.info('System data seeded successfully');
}
